### PR TITLE
Reload when modified

### PR DESCRIPTION
**Pull request by hbriese**
Currently reloading changes to the config requires restarting the service.
This change reloads the config if it's been modified (as determined by the last modified time of the file), unless the file no longer exists.

### CODE REVIEW

**Comment by hbriese** [comment]
Currently reloading changes to the config requires restarting the service.
This change reloads the config if it's been modified (as determined by the last modified time of the file), unless the file no longer exists.

**Comment by erpalma** [comment]
I would add a `Autoreload` option in the config file too for controlling the behavior of this PR. Can you also add a couple of words to the readme?

**Comment by hbriese** [comment]
Done. The option is enabled by default for new configs, but will fallback to disabled for existing users (without the 'Autoreload' option explicitly enabled) so that it doesn't break any assumptions someone may have relied upon

**Comment by erpalma** [comment]
Amazing, thank you!

**Pull request merged**
