### PR TITLE
openrc fix

### PR DESCRIPTION
**Pull request by Connor-Frank**
This maintains consistency with the install.sh script by using the virtualenv that the script sets up. The original version was using a different interpreter and complained about missing imports. Additionally, the new shebang now points to the correct openrc-run executable. These were the only changes needed for this script to work on Gentoo.

### CODE REVIEW

**Comment by Connor-Frank** [comment]
One more note: the install script doesn't recognize that it's operating on a Gentoo system, so the file needs to be copied to `/etc/init.d` manually. The issue seems to lie with the use of `pidof` to identify the init system. Maybe something like `whereis` would work better? I'm not sure how to fix that problem, but I can add an issue if that would help.

**Comment by erpalma** [comment]
I'm on Gentoo but with systemd. If you find a better way to identify the init system feel free to do a PR!

**Comment by Connor-Frank** [comment]
I'll take a look. Should I make a new PR with those changes, or would you rather I add them to this one?

**Comment by erpalma** [comment]
Let's keep all the openrc-related patches to this PR. Thank you!

**Comment by Connor-Frank** [comment]
I figured it out. Tested on:
- systemd (Fedora)
- runit (Void)
- openrc (Gentoo)
Sorry for the wait. Hope this helps.

**Pull request merged**
